spring:
  application:
    name: crud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/concept_funder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
    fetch-registry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
server:
  port: 19080

